# Generated by Django 3.0.5 on 2020-11-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='user_id',
        ),
    ]
