# Generated by Django 3.0.5 on 2020-10-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20201023_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
