# Generated by Django 3.0.5 on 2020-11-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20201111_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
    ]
