# Generated by Django 3.0.5 on 2020-10-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
