# Generated by Django 3.0.5 on 2020-11-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20201111_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsetting',
            name='id',
        ),
        migrations.AlterField(
            model_name='shopsetting',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shops.Shop'),
        ),
    ]
