# Generated by Django 3.0.5 on 2020-10-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20201026_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='user_id',
        ),
    ]
