# Generated by Django 3.0.5 on 2020-10-31 03:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20201027_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShopTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('delivery_start_time', models.TimeField(null=True)),
                ('delivery_end_time', models.TimeField(null=True)),
                ('pick_up_start_time', models.TimeField(null=True)),
                ('pick_up_end_time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop', verbose_name='shop_id')),
            ],
            options={
                'db_table': 'shop_timings',
            },
        ),
    ]
