# Generated by Django 3.0.5 on 2020-11-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_timezone_zone'),
        ('shops', '0006_auto_20201111_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsetting',
            name='time_zone',
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_settings.Zone', verbose_name='zone_id'),
        ),
    ]
