# Generated by Django 3.0.5 on 2020-11-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20201114_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
