# Generated by Django 3.0.5 on 2020-11-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20201118_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
