# Generated by Django 3.0.5 on 2020-11-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shopsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsetting',
            name='shop_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop', verbose_name='shop_id'),
        ),
    ]
