# Generated by Django 3.0.5 on 2020-11-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_shop_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
