# Generated by Django 3.0.5 on 2020-11-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20201104_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='currency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='food_prep_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='shop_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
