# Generated by Django 3.0.5 on 2020-11-11 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_total', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('delivery_fee', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop', verbose_name='shop_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('sub_total', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Cart', verbose_name='cart_id')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product_name')),
            ],
            options={
                'db_table': 'cart_line_items',
            },
        ),
        migrations.CreateModel(
            name='CartLineItemOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('CartLineItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.CartLineItem', verbose_name='cart_line_item_id')),
                ('productVariance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariance', verbose_name='product_variance_id')),
            ],
            options={
                'db_table': 'cart_line_item_options',
            },
        ),
    ]
