# Generated by Django 3.0.5 on 2020-11-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(blank=True, max_length=25, null=True)),
                ('province_name', models.CharField(blank=True, max_length=25, null=True)),
                ('gst', models.IntegerField(blank=True, null=True)),
                ('pst', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tax_settings',
            },
        ),
    ]
