# Generated by Django 3.0.5 on 2020-11-11 16:46

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('template_body', djrichtextfield.models.RichTextField(blank=True, null=True)),
                ('template_key', models.CharField(blank=True, max_length=255, null=True)),
                ('tokens', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(blank=True, max_length=25, null=True)),
                ('province_name', models.CharField(blank=True, max_length=25, null=True)),
                ('gst', models.IntegerField(blank=True, null=True)),
                ('pst', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tax_settings',
            },
        ),
    ]
