# Generated by Django 3.0.5 on 2020-11-14 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('zone_name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=6)),
                ('time_start', models.FloatField(max_length=11)),
                ('gmt_offset', models.IntegerField()),
                ('dst', models.CharField(max_length=1)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.Zone', verbose_name='zone_id')),
            ],
            options={
                'db_table': 'time_zones',
            },
        ),
    ]
