# Generated by Django 3.0.5 on 2020-11-07 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxSettings',
            new_name='TaxSetting',
        ),
    ]
