# Generated by Django 3.0.5 on 2020-11-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_auto_20201107_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('template_body', models.TextField(blank=True, null=True)),
                ('template_key', models.CharField(blank=True, max_length=255, null=True)),
                ('tokens', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
    ]
