# Generated by Django 3.0.5 on 2020-11-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_emailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template_body',
        ),
    ]
