# Generated by Django 3.0.5 on 2020-11-07 02:21

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_remove_emailtemplate_template_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template_body',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
