# Generated by Django 3.0.5 on 2020-10-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvarianceoption',
            name='component_price',
            field=models.IntegerField(default=0),
        ),
    ]
