# Generated by Django 3.0.5 on 2020-10-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201024_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
