# Generated by Django 3.0.5 on 2020-10-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_name',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
