# Generated by Django 3.0.5 on 2020-10-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201024_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
