# Generated by Django 3.0.5 on 2020-11-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201126_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
        migrations.AlterField(
            model_name='productvarianceoption',
            name='component_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
    ]
