# Generated by Django 3.0.5 on 2020-10-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201026_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarianceoption',
            name='variance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariance', verbose_name='variance_id'),
        ),
    ]
